#!/bin/bash

HIGHLIGHT="\e[7m"
NORMAL='\e[00m'

DIR=.
if [ "$1" != "" ]; then DIR=$1; fi
cd $DIR>/dev/null; echo -e "${HIGHLIGHT}Finding uncommited git repository in ${PWD}${NORMAL}"; cd ->/dev/null

find $DIR -name .git -and -type d -print0 | while IFS= read -r -d $'\0' line; do 
    REPO="$(dirname -- "$line"; printf x)" && REPO="${REPO%?x}"
    echo $REPO
    DIRTY=false
    
    # http://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git
    if ! git -C "$REPO" diff-index --quiet --cached HEAD ; then
	echo "Staged changes found"
	DIRTY=true
    fi
    if ! git -C "$REPO" diff-files --quiet ; then 
	echo "Unstaged changes found"
	DIRTY=true
    fi
    if [ $(git -C "$REPO" clean -n -d | wc -c) -ne 0 ]; then
	echo "Untracked, not ignored files found"
	DIRTY=true
    fi

    echo $DIRTY
    if [ "$DIRTY" = true ] ; then
	echo "DIRTY!"
    fi
    echo    
done
