#!/bin/bash

HIGHLIGHT="\e[7m"
NORMAL='\e[00m'
CMD="emacs"

DIR=.
if [ "$1" != "" ]; then DIR=$1; fi
cd $DIR>/dev/null; echo -e "${HIGHLIGHT}Finding uncommited git repository in ${PWD}${NORMAL}"; cd ->/dev/null

find $DIR -name .git -and -type d -print0 | while IFS= read -r -d $'\0' line; do 
    REPO="$(dirname -- "$line"; printf x)" && REPO="${REPO%?x}"
    DIRTY=false
    MSG=""
    
    # http://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git
    if ! git -C "$REPO" diff-index --quiet --cached HEAD ; then
	MSG="$MSG Staged changes found\n"
	DIRTY=true
    fi
    if ! git -C "$REPO" diff-files --quiet ; then 
        MSG="$MSG Unstaged changes found\n"
	DIRTY=true
    fi
    if [ $(git -C "$REPO" clean -n -d | wc -c) -ne 0 ]; then
	MSG="$MSG Untracked, not ignored files found\n"
	DIRTY=true
    fi

    if [ "$DIRTY" = true ] ; then
	echo "$REPO found to be dirty:"
	echo -ne $MSG
	echo    # (optional) move to a new line
    fi
    $CMD
done
